// <auto-generated />
using System;
using Cart_King.Connected_Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cart_King.Migrations
{
    [DbContext(typeof(CartKingDbContext))]
    partial class CartKingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cart_King.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Computer Accessories"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Graphics Cards"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "CPU Processors"
                        },
                        new
                        {
                            CategoryId = 4,
                            DisplayOrder = 4,
                            Name = "Custom Built PC's"
                        },
                        new
                        {
                            CategoryId = 5,
                            DisplayOrder = 5,
                            Name = "VR Headsets"
                        },
                        new
                        {
                            CategoryId = 6,
                            DisplayOrder = 6,
                            Name = "Consoles"
                        });
                });

            modelBuilder.Entity("Cart_King.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Cart_King.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Cart_King.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10235883?$l-large$&fmt=auto",
                            Name = "Keyboard",
                            Price = 19.99m,
                            ShortDescription = "Premium mechanical keyboard with RGB lighting",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10275017?$l-large$&fmt=auto",
                            Name = "ASUS GeForce RTX 5070 Ti TUF OC 16GB GDDR7",
                            Price = 989.99m,
                            ShortDescription = "Ultimate gaming graphics card with ray tracing",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10297321?$l-large$&fmt=auto",
                            Name = "AMD Ryzen 7 9850X3D 8 Core/16 Thread AM5 CPU",
                            Price = 449.99m,
                            ShortDescription = "High-performance processor for gaming and workstations",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10282274?$l-large$&fmt=auto",
                            Name = "MSI MPG Infinite Z3 AI Gaming PC - AMD Ryzen 9, RTX 5080, 2 TB SSD",
                            Price = 2699.99m,
                            ShortDescription = "This MSI Infinite Z3 packs a punch with its AMD Ryzen 9 Processor. That means it's great for top-tier gaming.",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10270714?$l-large$&fmt=auto",
                            Name = "META Quest 3S Mixed Reality Headset",
                            Price = 339.99m,
                            ShortDescription = "Dive into amazing experiences with the Meta Quest 3S",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            ImageUrl = "https://media.currys.biz/i/currysprod/10281815?$l-large$&fmt=auto",
                            Name = "NINTENDO Switch 2",
                            Price = 395.00m,
                            ShortDescription = "Game anywhere with Nintendo Switch 2. Inside, it's got beefed up processing and graphics, which means it's ready to take on massive games",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("Cart_King.Models.SalesDeal", b =>
                {
                    b.Property<int>("SalesDealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesDealId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SalesDealId");

                    b.HasIndex("ProductId");

                    b.ToTable("SalesDeals");
                });

            modelBuilder.Entity("Cart_King.Models.OrderItem", b =>
                {
                    b.HasOne("Cart_King.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Cart_King.Models.SalesDeal", b =>
                {
                    b.HasOne("Cart_King.Models.Product", "Product")
                        .WithMany("SalesDeals")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cart_King.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cart_King.Models.Product", b =>
                {
                    b.Navigation("SalesDeals");
                });
#pragma warning restore 612, 618
        }
    }
}
